#!/usr/bin/perl
## this script is making reference image links for markdown
## use this script in folder with images, just rename "images" to your folder name
## copy the output to your markdown document, you have the inline links and the reference links 


#image_link | zenity --width=800 --height=540 --text-info --title "Your markdown links"

print "Markdown Images reference links, put somewhere in document \n";
opendir(INFILE, "images") || die ("Unable to open directory");

#this line gets rid of . and ..<br>
@files = grep !/^\./, readdir(INFILE);

closedir(INFILE);

foreach $file (sort @files) {

#this was for making links from images and make html doc, see original script below
#print ("<font size=\"2\"face=\"arial\"><a href=/owner/$file>$+file</a></font>\n<br>");
	print ("[$file]: images\/$file \"$file\"\n");    
}

print ("\n");

print "Inline links, goes with the text \n";

opendir(INFILE, "images") || die ("Unable to open directory");

#this line gets rid of . and ..<br>
@files = grep !/^\./, readdir(INFILE);

closedir(INFILE);

foreach $file (sort @files) {
	print ("![$file][$file]\n");  
}


## Second try
$myperl = ("|", "zenity --width=800 --height=540 --text-info --title \"Your markdown links\"");
system("$myperl");


## This part is not working, piping from perl script into zenity the output
#open @files ,"|-", `zenity --width=800 --height=540 --text-info --title "Your markdown links"`;
#open $file, $result;
#open my $fh, "|-", q{zenity --title=Working --width=400 --progress --percentage=50 --no-cancel --auto-kill --auto-close}
