#!/bin/bash
 
DEST="./images"
mkdir -p $DEST
 
for file
    do
    if [ ! -e $file ]
        then
        continue
    fi
    to_name="$DEST/"$(echo $file | cut -f1 -d.)".jpg"
    convert -geometry $1x$1 -quality 100 "${file}" "${to_name}"
done
