#!/bin/bash
 
PERCENT="$1"
shift
	while (( "$#" )); do  
convert "$1" -resize "$PERCENT%" -quality 100 "resized_to_${PERCENT}%_$1"
	shift
done

exit 0



    
    


***

#!/bin/bash
  
  
DIRECTION="$1"
shift

case "$DIRECTION" in
"r")
  while (( "$#" )); do
	convert -rotate 90 -quality 100 "$1" "$1" 
	shift
  done
;;
"l")
  while (( "$#" )); do
	convert -rotate -90 -quality 100 "$1" "$1"
	shift
  done
;;
esac

exit 0
