#!/usr/bin/bash


## FRONT IMAGE ##

# Select file for front image
#
FILE=`zenity --file-selection --title="Select a File"`
cp $FILE ./front.jpg

# Add a border to the images
#
convert -scale 1020x1020 -border 2x2 front.jpg x-front.jpg

# Enter annotation for image front
#
EXT=`zenity --title="Image Description" --entry --text="Enter the image description"`

width=`identify -format %w x-front.jpg`; convert -background '#0008' -fill white -gravity center -size ${width}x50 caption:"$EXT" x-front.jpg +swap -gravity south -composite  x-front.jpg


## SIDE IMAGE ##


# Select file for side image
#
FILE=`zenity --file-selection --title="Select a File"`
cp $FILE ./side.jpg

# Add a border to the images
#
convert -scale 508x508   -border 2x2 side.jpg  x-side.jpg

# Enter annotation for image side
#
EXT=`zenity --title="Image Description" --entry --text="Enter the image description"`

width=`identify -format %w x-side.jpg`; convert -background '#0008' -fill white -gravity center -size ${width}x50 caption:"$EXT" x-side.jpg +swap -gravity south -composite  x-side.jpg




## TOP IMAGE ##

# Select file for top image
#
FILE=`zenity --file-selection --title="Select a File"`
cp $FILE ./top.jpg

# Add a border to the images
#
convert -scale 508x508   -border 2x2 top.jpg   x-top.jpg
EXT=`zenity --title="Image Description" --entry --text="Enter the image description"`

width=`identify -format %w x-top.jpg`; convert -background '#0008' -fill white -gravity center -size ${width}x50 caption:"$EXT" x-top.jpg +swap -gravity south -composite  x-top.jpg



#
# Then combine them
#
montage -tile 1x2 -mode Concatenate x-top.jpg   x-side.jpg  x-right.jpg
montage -tile 2x1 -mode Concatenate x-front.jpg x-right.jpg final.jpg


# Clean intermediate files
#
rm -f x-right.jpg x-front.jpg x-side.jpg x-top.jpg top.jpg front.jpg side.jpg
